 pipeline {
    agent any

  stages {
    stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
      }
  stage {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }


    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
    }
}

    stage ('package') {
      steps {
        script {
          sh 'echo "packaging App" '
        }
      }
    }
    }
}    

    stage ('package') {
      steps {
        script {
          sh 'echo "Deploying to dev" '
        }
      }

    stage("clean Up")
      steps {  
        cleanWS()
     }
    }
             
}  